# Generated by Django 5.2.6 on 2025-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_subject_remove_listing_screens_listing_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Office-Style', 'Office-Style'), ('Romantic-Style', 'Romantic-Style'), ('Family-Friendly', 'Family-Friendly'), ('Study-Focused', 'Study-Focused')], default='', max_length=200),
        ),
    ]
