# Generated by Django 5.2.6 on 2025-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='doctor',
            new_name='manager',
        ),
    ]
