# Generated by Django 5.2.6 on 2025-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_phone'),
        ('listings', '0007_rename_doctor_listing_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Manager',
        ),
    ]
